
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andre
 */
public class AcousticDrum extends javax.swing.JFrame {

    /**
     * Creates new form AcousticDrum
     */
    public AcousticDrum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKick = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        ChangeKitButton = new javax.swing.JButton();
        jTomHigh = new javax.swing.JButton();
        jTomMed = new javax.swing.JButton();
        jRide = new javax.swing.JButton();
        jCrash = new javax.swing.JButton();
        jTomLow = new javax.swing.JButton();
        jSnare = new javax.swing.JButton();
        jHihat = new javax.swing.JButton();
        jLabelBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jKick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKickActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(51, 153, 255));
        HomeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HomeButton.setForeground(java.awt.Color.white);
        HomeButton.setText("⮌ Return Home 🏠");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ChangeKitButton.setBackground(new java.awt.Color(255, 255, 0));
        ChangeKitButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChangeKitButton.setForeground(java.awt.Color.white);
        ChangeKitButton.setText("⮌ Change Kit  🥁");
        ChangeKitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeKitButtonActionPerformed(evt);
            }
        });

        jTomHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTomHighActionPerformed(evt);
            }
        });

        jTomMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTomMedActionPerformed(evt);
            }
        });

        jRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRideActionPerformed(evt);
            }
        });

        jCrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrashActionPerformed(evt);
            }
        });

        jTomLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTomLowActionPerformed(evt);
            }
        });

        jSnare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSnareActionPerformed(evt);
            }
        });

        jHihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHihatActionPerformed(evt);
            }
        });

        jLabelBanner.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabelBanner.setForeground(new java.awt.Color(102, 0, 0));
        jLabelBanner.setText("Acoustic Drum Kit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jSnare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHihat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRide, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jKick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTomHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTomMed, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jCrash, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTomLow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelBanner)
                        .addGap(117, 117, 117)
                        .addComponent(ChangeKitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChangeKitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBanner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTomHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTomMed, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jKick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jHihat, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSnare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRide, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTomLow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCrash, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param path
     * @param button
     * @param size_width
     * @param size_height 
     */
    void setImage(String path, JButton button, int size_width, int size_height){
        
        //sets the image icon of the button (resizes the image to fit the button)
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();  
        Image newimg = img.getScaledInstance( size_width, size_height,  java.awt.Image.SCALE_SMOOTH );  
        icon = new ImageIcon( newimg );
        button.setIcon(icon);
        validate();
        
    }
    
    /**
     * 
     * @param soundPath 
     */
    void pressButton(String soundPath){
        
        //plays the sound file
        try{
                AudioInputStream audioInputStreamED = AudioSystem.getAudioInputStream(new File(soundPath));
                Clip clipED = AudioSystem.getClip();
                clipED.open(audioInputStreamED);
                clipED.start();
            }
            
        catch (Exception ex){
                System.out.println("Error occured: drum button could not be played. " + ex);
            }
        
    }
    
    private void jKickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKickActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\Kick.wav");
        
    }//GEN-LAST:event_jKickActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        //Takes you back to the main menu
        MainMenu home= new MainMenu();
        home.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ChangeKitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeKitButtonActionPerformed

        //Takes you to the pick drum menu
        PickDrum pdrum= new PickDrum();
        pdrum.setVisible(true);
        setVisible(false);
        dispose();

    }//GEN-LAST:event_ChangeKitButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

          //Set the background color of the Window
          this.getContentPane().setBackground(Color.LIGHT_GRAY);
          
          //Set the image icons of the drum set buttons
          setImage(".\\Drum_Images\\Kick.png", jKick, 100, 100);
          setImage(".\\Drum_Images\\TomHigh.png", jTomHigh, 50, 50);
          setImage(".\\Drum_Images\\TomMed.png", jTomMed, 50, 50);
          setImage(".\\Drum_Images\\Crash.png", jCrash, 100, 150);
          setImage(".\\Drum_Images\\Ride.png", jRide, 100, 150);
          setImage(".\\Drum_Images\\Hihat.png", jHihat, 100, 150);
          setImage(".\\Drum_Images\\Snare.png", jSnare, 90, 90);
          setImage(".\\Drum_Images\\Tom.png", jTomLow, 100, 100);
          
    }//GEN-LAST:event_formWindowActivated

    private void jTomHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTomHighActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\TomHigh.wav");
        
    }//GEN-LAST:event_jTomHighActionPerformed

    private void jTomMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTomMedActionPerformed

        pressButton(".\\AcousticDrum_Samples\\TomMed.wav");
        
    }//GEN-LAST:event_jTomMedActionPerformed

    private void jCrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrashActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\Crash.wav");
        
    }//GEN-LAST:event_jCrashActionPerformed

    private void jRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRideActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\Ride.wav");        
        
    }//GEN-LAST:event_jRideActionPerformed

    private void jHihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHihatActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\Hihat.wav");        
        
    }//GEN-LAST:event_jHihatActionPerformed

    private void jSnareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSnareActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\Snare.wav");
        
    }//GEN-LAST:event_jSnareActionPerformed

    private void jTomLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTomLowActionPerformed
        
        pressButton(".\\AcousticDrum_Samples\\TomLow.wav");
        
    }//GEN-LAST:event_jTomLowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcousticDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcousticDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcousticDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcousticDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcousticDrum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeKitButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton jCrash;
    private javax.swing.JButton jHihat;
    private javax.swing.JButton jKick;
    private javax.swing.JLabel jLabelBanner;
    private javax.swing.JButton jRide;
    private javax.swing.JButton jSnare;
    private javax.swing.JButton jTomHigh;
    private javax.swing.JButton jTomLow;
    private javax.swing.JButton jTomMed;
    // End of variables declaration//GEN-END:variables
}
