
import java.awt.Color;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andre
 */
public class ElectronicDrum extends javax.swing.JFrame {

    /**
     * Creates new form ElectronicDrum
     */
    public ElectronicDrum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jRide = new javax.swing.JButton();
        jShaker = new javax.swing.JButton();
        jKick = new javax.swing.JButton();
        jTomLow = new javax.swing.JButton();
        jFXButton = new javax.swing.JButton();
        jSnare = new javax.swing.JButton();
        jTomHigh = new javax.swing.JButton();
        jClosedHihat = new javax.swing.JButton();
        jClap = new javax.swing.JButton();
        jCrash = new javax.swing.JButton();
        jOpenHihat = new javax.swing.JButton();
        jStick = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        ChangeKitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 255));
        jTextField1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Electronic Drum");

        jRide.setBackground(new java.awt.Color(255, 51, 255));
        jRide.setForeground(java.awt.Color.white);
        jRide.setText("Ride");
        jRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRideActionPerformed(evt);
            }
        });

        jShaker.setBackground(new java.awt.Color(255, 153, 0));
        jShaker.setForeground(java.awt.Color.white);
        jShaker.setText("Shaker");
        jShaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShakerActionPerformed(evt);
            }
        });

        jKick.setBackground(new java.awt.Color(51, 255, 51));
        jKick.setForeground(java.awt.Color.white);
        jKick.setText("Kick");
        jKick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKickActionPerformed(evt);
            }
        });

        jTomLow.setBackground(new java.awt.Color(51, 51, 255));
        jTomLow.setForeground(java.awt.Color.white);
        jTomLow.setText("Low");
        jTomLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTomLowActionPerformed(evt);
            }
        });

        jFXButton.setBackground(new java.awt.Color(204, 0, 51));
        jFXButton.setForeground(java.awt.Color.white);
        jFXButton.setText("FX");
        jFXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFXButtonActionPerformed(evt);
            }
        });

        jSnare.setBackground(new java.awt.Color(0, 204, 204));
        jSnare.setForeground(java.awt.Color.white);
        jSnare.setText("Snare");
        jSnare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSnareActionPerformed(evt);
            }
        });

        jTomHigh.setBackground(new java.awt.Color(51, 51, 255));
        jTomHigh.setForeground(java.awt.Color.white);
        jTomHigh.setText("High");
        jTomHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTomHighActionPerformed(evt);
            }
        });

        jClosedHihat.setBackground(new java.awt.Color(255, 0, 153));
        jClosedHihat.setForeground(java.awt.Color.white);
        jClosedHihat.setText("Closed");
        jClosedHihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClosedHihatActionPerformed(evt);
            }
        });

        jClap.setBackground(new java.awt.Color(255, 102, 51));
        jClap.setForeground(java.awt.Color.white);
        jClap.setText("Clap");
        jClap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClapActionPerformed(evt);
            }
        });

        jCrash.setBackground(new java.awt.Color(255, 51, 255));
        jCrash.setForeground(java.awt.Color.white);
        jCrash.setText("Crash");
        jCrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrashActionPerformed(evt);
            }
        });

        jOpenHihat.setBackground(new java.awt.Color(255, 0, 204));
        jOpenHihat.setForeground(java.awt.Color.white);
        jOpenHihat.setText("Open");
        jOpenHihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenHihatActionPerformed(evt);
            }
        });

        jStick.setBackground(new java.awt.Color(153, 0, 255));
        jStick.setForeground(java.awt.Color.white);
        jStick.setText("Stick");
        jStick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStickActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(51, 153, 255));
        HomeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HomeButton.setForeground(java.awt.Color.white);
        HomeButton.setText("⮌ Return Home 🏠");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ChangeKitButton.setBackground(new java.awt.Color(255, 255, 0));
        ChangeKitButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChangeKitButton.setForeground(java.awt.Color.white);
        ChangeKitButton.setText("⮌ Change Kit  🥁");
        ChangeKitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeKitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jShaker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jKick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFXButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSnare, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jClosedHihat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jClap, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTomLow, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTomHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCrash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jOpenHihat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jStick, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(ChangeKitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChangeKitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRide, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTomLow, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTomHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCrash, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShaker, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFXButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClosedHihat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOpenHihat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKick, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSnare, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClap, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStick, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void pressPad(String drumPath){
        
        //plays sound files
        try{
                AudioInputStream audioInputStreamED = AudioSystem.getAudioInputStream(new File(drumPath));
                Clip clipED = AudioSystem.getClip();
                clipED.open(audioInputStreamED);
                clipED.start();
            }
            
        catch (Exception ex){
                System.out.println("Error occured: pad could not be played. " + ex);
            }
    }
    
    private void jKickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKickActionPerformed
        
        pressPad(".\\Drum_Samples\\Kick.wav");
        
    }//GEN-LAST:event_jKickActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        //Takes you back to the main menu
        MainMenu home= new MainMenu();
        home.setVisible(true);
        setVisible(false);
        dispose();

    }//GEN-LAST:event_HomeButtonActionPerformed

    private void jShakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShakerActionPerformed
        
        pressPad(".\\Drum_Samples\\Shaker.wav");
        
    }//GEN-LAST:event_jShakerActionPerformed

    private void jRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRideActionPerformed
        
        pressPad(".\\Drum_Samples\\Ride.wav");
        
    }//GEN-LAST:event_jRideActionPerformed

    private void jSnareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSnareActionPerformed
        
        pressPad(".\\Drum_Samples\\Snare.wav");
        
    }//GEN-LAST:event_jSnareActionPerformed

    private void jFXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFXButtonActionPerformed
        
        pressPad(".\\Drum_Samples\\FX.wav");
        
    }//GEN-LAST:event_jFXButtonActionPerformed

    private void jTomLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTomLowActionPerformed
        
        pressPad(".\\Drum_Samples\\TomLow.wav");
        
    }//GEN-LAST:event_jTomLowActionPerformed

    private void jTomHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTomHighActionPerformed
        
        pressPad(".\\Drum_Samples\\TomHigh.wav");
        
    }//GEN-LAST:event_jTomHighActionPerformed

    private void jCrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrashActionPerformed
        
        pressPad(".\\Drum_Samples\\Crash.wav");
        
    }//GEN-LAST:event_jCrashActionPerformed

    private void jOpenHihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenHihatActionPerformed
        
        pressPad(".\\Drum_Samples\\OpenHihat.wav");
        
    }//GEN-LAST:event_jOpenHihatActionPerformed

    private void jClosedHihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClosedHihatActionPerformed
        
        pressPad(".\\Drum_Samples\\ClosedHihat.wav");
        
    }//GEN-LAST:event_jClosedHihatActionPerformed

    private void jClapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClapActionPerformed
        
        pressPad(".\\Drum_Samples\\Clap.wav");
        
    }//GEN-LAST:event_jClapActionPerformed

    private void jStickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStickActionPerformed
        
        pressPad(".\\Drum_Samples\\Stick.wav");
        
    }//GEN-LAST:event_jStickActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        //Sets background of current window
        this.getContentPane().setBackground(Color.black);
        
    }//GEN-LAST:event_formWindowActivated

    private void ChangeKitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeKitButtonActionPerformed
        
        //Takes you back to the pick drum menu
        PickDrum pdrum= new PickDrum();
        pdrum.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_ChangeKitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectronicDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectronicDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectronicDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectronicDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectronicDrum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeKitButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton jClap;
    private javax.swing.JButton jClosedHihat;
    private javax.swing.JButton jCrash;
    private javax.swing.JButton jFXButton;
    private javax.swing.JButton jKick;
    private javax.swing.JButton jOpenHihat;
    private javax.swing.JButton jRide;
    private javax.swing.JButton jShaker;
    private javax.swing.JButton jSnare;
    private javax.swing.JButton jStick;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jTomHigh;
    private javax.swing.JButton jTomLow;
    // End of variables declaration//GEN-END:variables
}
