
import java.awt.Color;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andre
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuBanner = new javax.swing.JTextField();
        PianoButton = new javax.swing.JButton();
        MainMenuTitle = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        DrumButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        MainMenuBanner.setEditable(false);
        MainMenuBanner.setBackground(new java.awt.Color(0, 153, 255));
        MainMenuBanner.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        MainMenuBanner.setForeground(java.awt.Color.white);
        MainMenuBanner.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MainMenuBanner.setText("Basement Band");

        PianoButton.setBackground(new java.awt.Color(51, 51, 51));
        PianoButton.setForeground(java.awt.Color.white);
        PianoButton.setText("Piano 🎹");
        PianoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PianoButtonActionPerformed(evt);
            }
        });

        MainMenuTitle.setEditable(false);
        MainMenuTitle.setBackground(new java.awt.Color(0, 153, 255));
        MainMenuTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        MainMenuTitle.setForeground(java.awt.Color.white);
        MainMenuTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MainMenuTitle.setText("Main Menu");

        ExitButton.setBackground(new java.awt.Color(255, 0, 0));
        ExitButton.setForeground(java.awt.Color.white);
        ExitButton.setText("Exit 🚪");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        DrumButton.setBackground(new java.awt.Color(255, 255, 0));
        DrumButton.setForeground(new java.awt.Color(0, 0, 0));
        DrumButton.setText("Drum 🥁");
        DrumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrumButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainMenuBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DrumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PianoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(MainMenuBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PianoButton)
                .addGap(18, 18, 18)
                .addComponent(DrumButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PianoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PianoButtonActionPerformed
        
        //Button behaviour for taking you to the piano page, closes this window
        //and opens a new one for the piano
        VirtualPiano vpiano= new VirtualPiano();
        vpiano.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_PianoButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        
        //closes the current window when the exit is called
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        //sets background color of the window
        this.getContentPane().setBackground(Color.black);
        
    }//GEN-LAST:event_formWindowActivated

    private void DrumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrumButtonActionPerformed
        
        //Behaviour for the drum button that'll take you to a drum kit selection
        //menu screen. Closes current window, opens new one.
        PickDrum pdrum= new PickDrum();
        pdrum.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_DrumButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DrumButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField MainMenuBanner;
    private javax.swing.JTextField MainMenuTitle;
    private javax.swing.JButton PianoButton;
    // End of variables declaration//GEN-END:variables
}
