
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andre
 */
public class PickDrum extends javax.swing.JFrame {

    /**
     * Creates new form PickDrum
     */
    public PickDrum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PickDrumTitle = new javax.swing.JTextField();
        AcouDrum = new javax.swing.JButton();
        ElecDrum = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PickDrumTitle.setEditable(false);
        PickDrumTitle.setBackground(java.awt.Color.black);
        PickDrumTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PickDrumTitle.setForeground(java.awt.Color.white);
        PickDrumTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PickDrumTitle.setText("Select a drum kit:");

        AcouDrum.setBackground(new java.awt.Color(255, 255, 102));
        AcouDrum.setText("Acoustic");
        AcouDrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcouDrumActionPerformed(evt);
            }
        });

        ElecDrum.setBackground(new java.awt.Color(102, 255, 102));
        ElecDrum.setText("Electonic");
        ElecDrum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ElecDrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElecDrumActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(51, 153, 255));
        HomeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HomeButton.setForeground(java.awt.Color.white);
        HomeButton.setText("⮌ Return Home 🏠");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PickDrumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AcouDrum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ElecDrum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PickDrumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcouDrum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ElecDrum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElecDrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElecDrumActionPerformed
        
        //Button behaviour for taking you to a new page that renders the view
        //for the electronic drum kit, closes current window.
        ElectronicDrum edrum= new ElectronicDrum();
        edrum.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_ElecDrumActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        //sets background color of window
        this.getContentPane().setBackground(Color.black);
        
    }//GEN-LAST:event_formWindowActivated

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed

        //Takes you back to the Main Menu
        MainMenu home= new MainMenu();
        home.setVisible(true);
        setVisible(false);
        dispose();

    }//GEN-LAST:event_HomeButtonActionPerformed

    private void AcouDrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcouDrumActionPerformed
        
        //Takes you to the view that renders the Acoustic Drum layout
        AcousticDrum aDrum= new AcousticDrum();
        aDrum.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_AcouDrumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickDrum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickDrum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcouDrum;
    private javax.swing.JButton ElecDrum;
    private javax.swing.JButton HomeButton;
    private javax.swing.JTextField PickDrumTitle;
    // End of variables declaration//GEN-END:variables
}
