/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andre
 */

import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.io.*;
import javax.swing.JOptionPane;

public class VirtualPiano extends javax.swing.JFrame {

    /**
     * Creates new form VirtualPiano
     */
    public VirtualPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCSharpKey = new javax.swing.JButton();
        jCKey = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jEPianoCheck = new javax.swing.JCheckBox();
        jSteelDrumCheck = new javax.swing.JCheckBox();
        jDSharpKey = new javax.swing.JButton();
        jDKey = new javax.swing.JButton();
        jEKey = new javax.swing.JButton();
        jFSharpKey = new javax.swing.JButton();
        jFKey = new javax.swing.JButton();
        jGSharpKey = new javax.swing.JButton();
        jGKey = new javax.swing.JButton();
        jBbKey = new javax.swing.JButton();
        jAKey = new javax.swing.JButton();
        jBKey = new javax.swing.JButton();
        jC1Key = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        jCSharpKey.setBackground(new java.awt.Color(0, 0, 0));
        jCSharpKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCSharpKey.setForeground(java.awt.Color.white);
        jCSharpKey.setText("C#");
        jCSharpKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jCSharpKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSharpKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jCSharpKey);
        jCSharpKey.setBounds(70, 110, 70, 160);

        jCKey.setBackground(java.awt.Color.white);
        jCKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCKey.setText("C");
        jCKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jCKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jCKey);
        jCKey.setBounds(30, 110, 73, 300);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 260, 90);

        buttonGroup1.add(jEPianoCheck);
        jEPianoCheck.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jEPianoCheck.setForeground(new java.awt.Color(255, 255, 255));
        jEPianoCheck.setSelected(true);
        jEPianoCheck.setText("Electronic Piano");
        jEPianoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEPianoCheckActionPerformed(evt);
            }
        });
        jPanel1.add(jEPianoCheck);
        jEPianoCheck.setBounds(510, 20, 120, 24);

        buttonGroup1.add(jSteelDrumCheck);
        jSteelDrumCheck.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSteelDrumCheck.setForeground(new java.awt.Color(255, 255, 255));
        jSteelDrumCheck.setText("Steel Drum");
        jSteelDrumCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSteelDrumCheckActionPerformed(evt);
            }
        });
        jPanel1.add(jSteelDrumCheck);
        jSteelDrumCheck.setBounds(510, 70, 120, 24);

        jDSharpKey.setBackground(new java.awt.Color(0, 0, 0));
        jDSharpKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jDSharpKey.setForeground(java.awt.Color.white);
        jDSharpKey.setText("D#");
        jDSharpKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jDSharpKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDSharpKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jDSharpKey);
        jDSharpKey.setBounds(150, 110, 73, 160);

        jDKey.setBackground(java.awt.Color.white);
        jDKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jDKey.setText("D");
        jDKey.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jDKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jDKey);
        jDKey.setBounds(110, 110, 73, 300);

        jEKey.setBackground(java.awt.Color.white);
        jEKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEKey.setText("E");
        jEKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jEKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jEKey);
        jEKey.setBounds(190, 110, 73, 300);

        jFSharpKey.setBackground(new java.awt.Color(0, 0, 0));
        jFSharpKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jFSharpKey.setForeground(java.awt.Color.white);
        jFSharpKey.setText("F#");
        jFSharpKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jFSharpKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFSharpKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jFSharpKey);
        jFSharpKey.setBounds(310, 110, 73, 160);

        jFKey.setBackground(java.awt.Color.white);
        jFKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jFKey.setText("F");
        jFKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jFKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jFKey);
        jFKey.setBounds(270, 110, 73, 300);

        jGSharpKey.setBackground(new java.awt.Color(0, 0, 0));
        jGSharpKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jGSharpKey.setForeground(new java.awt.Color(255, 255, 255));
        jGSharpKey.setText("G#");
        jGSharpKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jGSharpKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGSharpKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jGSharpKey);
        jGSharpKey.setBounds(390, 110, 68, 160);

        jGKey.setBackground(java.awt.Color.white);
        jGKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jGKey.setText("G");
        jGKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jGKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jGKey);
        jGKey.setBounds(350, 110, 73, 300);

        jBbKey.setBackground(new java.awt.Color(0, 0, 0));
        jBbKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBbKey.setForeground(java.awt.Color.white);
        jBbKey.setText("Bb");
        jBbKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBbKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jBbKey);
        jBbKey.setBounds(470, 110, 70, 160);

        jAKey.setBackground(java.awt.Color.white);
        jAKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jAKey.setText("A");
        jAKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jAKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jAKey);
        jAKey.setBounds(430, 110, 73, 300);

        jBKey.setBackground(java.awt.Color.white);
        jBKey.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBKey.setText("B");
        jBKey.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jBKey);
        jBKey.setBounds(510, 110, 70, 300);

        jC1Key.setBackground(java.awt.Color.white);
        jC1Key.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jC1Key.setText("C1");
        jC1Key.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jC1Key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC1KeyActionPerformed(evt);
            }
        });
        jPanel1.add(jC1Key);
        jC1Key.setBounds(590, 110, 70, 300);

        HomeButton.setBackground(new java.awt.Color(51, 153, 255));
        HomeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HomeButton.setForeground(java.awt.Color.white);
        HomeButton.setText("⮌ Return Home 🏠");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButton);
        HomeButton.setBounds(30, 30, 160, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 720, 440);

        setBounds(0, 0, 755, 498);
    }// </editor-fold>//GEN-END:initComponents

    void pressKey(String pianoPath, String steelDrumPath){
        
        //The set of sounds used will differ based on what preset is selected
        if (jEPianoCheck.isSelected()){
            try{
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(pianoPath));
                Clip clip = AudioSystem.getClip();
                clip.open(audioInputStream);
                clip.start();
            }
            
            catch (Exception ex){
                System.out.println("Error occured: key could not be played. " + ex);
            }
        }
        
        if (jSteelDrumCheck.isSelected()){
            try{
                AudioInputStream audioInputStreamSD = AudioSystem.getAudioInputStream(new File(steelDrumPath));
                Clip clipSD = AudioSystem.getClip();
                clipSD.open(audioInputStreamSD);
                clipSD.start();
            }
            
            catch (Exception ex){
                System.out.println("Error occured: key could not be played.");
            }
        }
        
    }
       
    private void jCKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\C.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\C_Drum.wav");
        
    }//GEN-LAST:event_jCKeyActionPerformed

    private void jEPianoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEPianoCheckActionPerformed
        
        //sets up a listener to see that this box is checked
        
    }//GEN-LAST:event_jEPianoCheckActionPerformed

    private void jCSharpKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSharpKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\C_s.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\Cq_Drum.wav");
        
    }//GEN-LAST:event_jCSharpKeyActionPerformed

    private void jDKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDKeyActionPerformed

        pressKey(".\\Z_Music_Notes\\Music_Notes\\D.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\D_Drum.wav");
        
    }//GEN-LAST:event_jDKeyActionPerformed

    private void jDSharpKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDSharpKeyActionPerformed

        pressKey(".\\Z_Music_Notes\\Music_Notes\\D_s.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\Dq_Drum.wav");
        
    }//GEN-LAST:event_jDSharpKeyActionPerformed

    private void jEKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEKeyActionPerformed

        pressKey(".\\Z_Music_Notes\\Music_Notes\\E.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\E_Drum.wav");
        
    }//GEN-LAST:event_jEKeyActionPerformed

    private void jFKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\F.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\F_Drum.wav");
        
    }//GEN-LAST:event_jFKeyActionPerformed

    private void jGKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\G.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\G_Drum.wav");
        
    }//GEN-LAST:event_jGKeyActionPerformed

    private void jFSharpKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFSharpKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\F_s.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\Fq_Drum.wav");
        
    }//GEN-LAST:event_jFSharpKeyActionPerformed

    private void jGSharpKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGSharpKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\G_s.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\Gq_Drum.wav");
        
    }//GEN-LAST:event_jGSharpKeyActionPerformed

    private void jAKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\A.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\A_Drum.wav");
        
    }//GEN-LAST:event_jAKeyActionPerformed

    private void jBbKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\Bb.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\Bb_Drum.wav");
        
    }//GEN-LAST:event_jBbKeyActionPerformed

    private void jC1KeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC1KeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\C1.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\C1_Drum.wav");
        
    }//GEN-LAST:event_jC1KeyActionPerformed

    private void jBKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKeyActionPerformed
        
        pressKey(".\\Z_Music_Notes\\Music_Notes\\B.wav", ".\\Z_Music_Notes\\Music_Notes\\Steel_Drum\\B_Drum.wav");
        
    }//GEN-LAST:event_jBKeyActionPerformed

    private void jSteelDrumCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSteelDrumCheckActionPerformed
        
        //sets up a listener to see that this box is checked
        
    }//GEN-LAST:event_jSteelDrumCheckActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        //sets the background color of the window
        this.getContentPane().setBackground(Color.black);
        
    }//GEN-LAST:event_formWindowActivated

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        
        //Button behaviour for button that returns user to main menu
        MainMenu home= new MainMenu();
        home.setVisible(true);
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_HomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAKey;
    private javax.swing.JButton jBKey;
    private javax.swing.JButton jBbKey;
    private javax.swing.JButton jC1Key;
    private javax.swing.JButton jCKey;
    private javax.swing.JButton jCSharpKey;
    private javax.swing.JButton jDKey;
    private javax.swing.JButton jDSharpKey;
    private javax.swing.JButton jEKey;
    private javax.swing.JCheckBox jEPianoCheck;
    private javax.swing.JButton jFKey;
    private javax.swing.JButton jFSharpKey;
    private javax.swing.JButton jGKey;
    private javax.swing.JButton jGSharpKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jSteelDrumCheck;
    // End of variables declaration//GEN-END:variables
}
